Add config file comments/documentation
shokme/laravel-scout-meilisearch pull request #54
Opened 2020-10-23 12:09 UTC by bensherred

This PR is a non-breaking change and is more of a nice to have. Most of the default Laravel config files come with an explanation for each value. This makes it easier to know exactly what the value is used for and so the user doesn't have to check the documentation every time.

I've added some basic documentation to the config file that gets published (if the user chooses to).

2020-10-23 14:01 UTC, shokme requested changes

2020-10-23 14:01 UTC, shokme commented on config/config.php
> +    | environemtn.
```suggestion
    | environment.
```

2020-10-23 14:02 UTC, shokme commented
Hello @bensherred 

This is so cool ! Thank you 😄

2020-10-23 14:03 UTC, bensherred commented
No worries! Just a nice little touch 😄

2020-10-23 14:03 UTC, shokme approved these changes

2020-10-23 14:04 UTC, merged

2020-10-25 11:53 UTC, curquiza commented
Awesome @bensherred! Thank you so much for this!