Add PHP 7.2 CI tests
shokme/laravel-scout-meilisearch pull request #92
Opened 2021-02-02 20:37 UTC by mmachatschek

This adds PHP 7.2 CI tests.

The `composer.json` tells us, that the version is supported but we do not actually test this.

PS: If we want to upgrade the minimum dependency to `php:^7.3|^8.0` I would gladly do so. PHP 7.2 is not receiving any bugfixes and security fixes anymore and we would encorage the users to upgrade their stack to a supported version.

2021-02-02 22:27 UTC, shokme commented
@mmachatschek we can keep the 7.2 like the sdk does: https://github.com/meilisearch/meilisearch-php/issues/136

2021-02-03 10:52 UTC, curquiza requested changes
Hello @mmachatschek thanks for your PR :)

I agree with @shokme, let's keep the 7.2 support for the moment. If you disagree with this choice, an issue (https://github.com/meilisearch/meilisearch-php/issues/136) is available here (I will reopen it if we need to debate).

Also, to merge your PR, I need you to update the bors.toml file (https://github.com/meilisearch/meilisearch-laravel-scout/blob/master/bors.toml) by adding the `'tests (php 7.2)'` in the `status` field 😊

2021-02-03 11:29 UTC, mmachatschek commented
> Also, to merge your PR, I need you to update the bors.toml file (https://github.com/meilisearch/meilisearch-laravel-scout/blob/master/bors.toml) by adding the 'tests (php 7.2)' in the status field blush

@curquiza done.

> I agree with @shokme, let's keep the 7.2 support for the moment. If you disagree with this choice, an issue (meilisearch/meilisearch-php#136) is available here (I will reopen it if we need to debate) slightly_smiling_face We like having the community opinion!

No need for that. I agree as long as everything aligns with the dependency tree (laravel/scout and meilisearch/meilisearch/php) :+1:

2021-02-03 12:27 UTC, curquiza approved these changes
Thanks @mmachatschek for this addition! 😄 

bors merge

2021-02-03 12:28 UTC, merged